name: Playwright Tests

on:
  push:
    branches:
      - feature1
  workflow_dispatch:

permissions:
  contents: write

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Pull Docker image
        run: docker pull surya212299/playwright_demo:latest

      - name: Run Playwright inside Docker
        run: docker run --name playwright-container surya212299/playwright_demo:latest

      - name: Copy Allure results
        if: always()
        run: docker cp playwright-container:/app/allure-results ./allure-results

      - name: Install Allure CLI
        if: always()
        run: npm install -g allure-commandline

      - name: Generate Allure report
        if: always()
        run: allure generate allure-results -o allure-report --clean

      - name: Upload Allure report
        uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: allure-report
          path: allure-report/

      - name: Deploy report
        if: always()
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./allure-report